---
permalink: task-deploy-bluexp-backup-and-recovery-for-vms.html 
sidebar: sidebar 
keywords: deploy, bluexp, backup, recovery for VMs 
summary: 要保护虚拟机上的VM、数据存储库和应用程序一致的数据库、您必须为VM部署BlueXP备份和恢复。 
---
= 为VM部署BlueXP备份和恢复
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
要保护虚拟机上的VM、数据存储库和应用程序一致的数据库、您必须为VM部署BlueXP备份和恢复。

.开始之前
++++

[NOTE]
====
VMware vCenter 8.0及更高版本支持OVA部署。

====
* 您必须已阅读部署要求。
* 您必须在AWS上运行受支持的VMC版本。
* 您必须已在AWS环境上配置和设置VMC。
* 您必须已设置ESXi主机、以便为VM执行BlueXP备份和恢复。
* 您必须已下载VM的BlueXP备份和恢复 `.tar` 文件
* 您必须知道AWS上的VMC实例的登录身份验证详细信息。
* 您必须拥有一个包含有效公共密钥和专用密钥文件的证书。有关详细信息、请参见存储证书管理一节下的文章。
* 您必须已注销并关闭vSphere客户端的所有浏览器会话、并删除浏览器缓存、以避免在为VM部署BlueXP备份和恢复期间出现任何浏览器缓存问题描述。
* 您必须已在 vCenter 中启用传输层安全（ TLS ）。请参见 VMware 文档。


在与vCenter相同的时区为VM部署BlueXP备份和恢复。

.步骤
. 对于VMware vCenter 7.0.3及更高版本、请按照下载开放式虚拟设备(OVA)一节中的步骤将证书导入到vCenter中。
. 在浏览器中，导航到 VMware vSphere vCenter 。
. 登录到* VMware vCenter单点登录页面*。
. 在导航器窗格中，右键单击作为虚拟机的有效父对象的任何清单对象，例如数据中心，集群或主机，然后选择 * 部署 OVF 模板 * 以启动 VMware Deploy 向导。
. 提取 `.tar` 文件、其中包含 `.ova` 文件。在*选择OVF模板*页面上、指定的位置 `.ova` 文件 `.tar` 已提取文件夹。
. 单击 * 下一步 * 。
. 在 * 选择名称和文件夹 * 页面上，输入虚拟机或 vApp 的唯一名称，并选择部署位置，然后单击 * 下一步 * 。
+
此步骤指定导入位置 `.ova` 文件到vCenter中。虚拟机的默认名称与选定的名称相同 `.ova` 文件如果更改默认名称、请选择一个在AWS VM上的每个VMC文件夹中唯一的名称。

+
VM 的默认部署位置是启动向导的清单对象。

. 在 * 选择资源 * 页面上，选择要运行已部署 VM 模板的资源，然后单击 * 下一步 * 。
. 在*查看详细信息*页面上、验证 `.ova` 模板详细信息、然后单击*下一步*。
. 在 * 许可协议 * 页面上，选中 * 我接受所有许可协议 * 复选框。
. 在 * 选择存储 * 页面上，定义为已部署的 OVF 模板存储文件的位置和方式。
+
.. 选择 VMDK 的磁盘格式。
.. 选择 VM 存储策略。
+
只有在目标资源上启用了存储策略时，此选项才可用。

.. 选择一个数据存储库以存储已部署的 OVA 模板。
+
配置文件和虚拟磁盘文件存储在数据存储库中。

+
选择一个足以容纳虚拟机或 vApp 以及所有关联虚拟磁盘文件的数据存储库。



. 在 * 选择网络 * 页面上，执行以下操作：
+
.. 选择一个源网络并将其映射到一个目标网络。
+
源网络列列出了 OVA 模板中定义的所有网络。

.. 在 * IP 分配设置 * 部分中，选择所需的 IP 协议，然后单击 * 下一步 * 。
+
VM的BlueXP备份和恢复支持一个网络接口。如果需要多个网络适配器，则必须手动设置。



. 在 * 自定义模板 * 页面上，执行以下操作：
+
.. 在 * 注册到现有 vCenter * 部分中，输入虚拟设备的 vCenter 名称和 vCenter 凭据。
+
在* vCenter用户名*字段中、以"域\用户名"格式输入用户名。

.. 在*为VM凭据创建BlueXP备份和恢复*部分中、输入本地凭据。
+
在 * 用户名 * 字段中，输入本地用户名；不包括域详细信息。

+
[IMPORTANT]
====
记下您指定的用户名和密码。如果要稍后修改适用于VM的BlueXP备份和恢复配置、则需要使用这些凭据。

====
.. 输入maint用户的凭据。
.. 在 * 设置网络属性 * 中，输入主机名。
+
... 在 * 设置 IPv4 网络属性 * 部分中，输入网络信息，例如 IPv4 地址， IPv4 网络掩码， IPv4 网关， IPv4 主 DNS ， IPv4 二级 DNS ， 和 IPv4 搜索域。
+
[IMPORTANT]
====
如果要继续使用DHCP作为网络配置、可以跳过这些步骤、并将设置网络属性部分中的条目留空。

====


.. 在 * 设置日期和时间 * 中，选择 vCenter 所在的时区。


. 在 * 准备完成 * 页面上，查看此页面并单击 * 完成 * 。
+
所有主机都必须配置 IP 地址（不支持 FQDN 主机名）。在部署之前， Deploy 操作不会验证您的输入。

+
在等待 OVF 导入和部署任务完成时，您可以从 " 近期任务 " 窗口查看部署进度。

+
成功为VM部署BlueXP备份和恢复后、该VM将部署为Linux VM、并注册到vCenter中、然后安装VMware vSphere客户端。

. 导航到部署了虚拟机BlueXP备份和恢复的虚拟机，单击*摘要*选项卡，然后单击*开机*框启动虚拟设备。
. 启动虚拟机的BlueXP备份和恢复时，右键单击为虚拟机部署的BlueXP备份和恢复，选择*子操作系统*，然后单击*安装VMware工具*。

