---
permalink: task-restore-virtual-machines-from-amazon-fsx.html 
sidebar: sidebar 
keywords: restore, virtual machines, amazon fsx 
summary: 还原虚拟机时、您可以使用所选的备份副本覆盖现有内容、也可以创建虚拟机的副本。 
---
= 从Amazon FSx还原虚拟机
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
还原虚拟机时、您可以使用所选的备份副本覆盖现有内容、也可以创建虚拟机的副本。

.开始之前
* 必须存在备份。
+
您必须已使用BlueXP备份和恢复为虚拟机创建备份、然后才能还原虚拟机。

+
[NOTE]
====
如果虚拟机的Snapshot副本是由虚拟机的BlueXP备份和恢复以外的软件执行的、则还原操作无法成功完成。

====
* 虚拟机不得在传输中。
+
要还原的虚拟机不能处于vMotion或Storage vMotion状态。

* HA配置错误。
+
在将备份还原到其他位置之前，请确保 vCenter ESXi 主机摘要屏幕上未显示 HA 配置错误。



.关于此任务
* 虚拟机已取消注册并重新注册。
+
虚拟机的还原操作会取消注册原始虚拟机、从备份Snapshot副本还原虚拟机、并在同一ESXi服务器上注册具有相同名称和配置的还原虚拟机。还原后、必须手动将虚拟机添加到资源组。

* 还原数据存储库
+
您无法还原数据存储库、但可以还原数据存储库中的任何虚拟机。

* 虚拟机的VMware一致性快照失败。
+
即使虚拟机的VMware一致性快照发生故障、也会备份该虚拟机。您可以在还原向导中查看备份副本中包含的实体，并将其用于还原操作。



.步骤
. 在VMware vSphere Web Client GUI中，单击工具栏中的*菜单*，单击*清单*，然后选择*虚拟机和模板*。
. 在左侧导航器窗格中，右键单击一个*Virtual Machine*，然后在NetApp下拉列表中选择*Cloud Backup*，然后选择*Restore*以启动向导。
. 在 * 还原 * 向导的 * 选择备份 * 页面上，选择要还原的备份 Snapshot 副本。
+
您可以搜索特定备份名称或部分备份名称，也可以通过单击筛选器图标并选择日期和时间范围，选择是否要包含 VMware Snapshot 的备份，是否要挂载备份以及位置来筛选备份列表。单击 * 确定 * 以返回到向导。

. 在*选择范围*页面上，在*还原范围*字段中选择*整个虚拟机*，然后选择还原位置，并输入应挂载备份的目标ESXi信息。
+
还原部分备份时，还原操作会跳过 * 选择范围 * 页面。

. 如果要在还原操作后启动虚拟机，请启用*Restart VM*复选框。
. 在 * 选择位置 * 页面上，选择已还原数据存储库的位置。
. 查看“*摘要*”页，然后单击“*完成*”。
. *可选*：单击屏幕底部的*近期任务*来监视操作进度。


.完成后
* 将已还原的虚拟机添加到资源组。
+
尽管虚拟机已还原、但它们不会自动添加到以前的资源组中。因此、您必须手动将已还原的虚拟机添加到相应的资源组。


